title: Products
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: price
            field:
              input_type: number
              antlers: false
              type: text
              display: Price
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: type
            field:
              options:
                subscription: Subscription
                single: 'Single Product'
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: Type
              icon: select
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: asset
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Asset
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
